name: Main Branch Push
on:
  push:
    branches:
      - main
      - master
jobs:
  main-branch-push:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: |
        go test ./...
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...